pluginManagement {
    plugins {
        id 'org.springframework.boot' version "${springBootVersion}"
        id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
        id 'org.asciidoctor.jvm.convert' version "${asciidoctorConvertVersion}"
        id 'com.diffplug.spotless' version "${spotlessVersion}"
    }
}

rootProject.name = 'calfit'

// Core 모듈
include 'core:core-enum'
include 'core:core-api'
include 'core:domain-payment'
include 'core:domain-billing'
include 'core:domain-career'
include 'core:domain-finance'
include 'core:domain-user'
include 'core:domain-workspace'
include 'core:domain-calendar'
include 'core:domain-meeting-room'
include 'core:domain-announcement-board'
include 'core:domain-applicant'
include 'core:domain-application'

// Storage 모듈
include 'storage:db-core'

// Support 모듈
include 'support:logging'
include 'support:monitoring'
include 'support:security'
include 'support:event'
include 'support:error'
include 'support:email'

// Client 모듈
include 'clients:client-example'
include 'clients:google-calendar'
include 'core:domain-announcment-board'
