version: "3.8"

services:
  core-api:
    image: calfit-api
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    container_name: core-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - calfit-net

networks:
  calfit-net:
    external: true