version: "3.8"

services:
  core-api:
    image: calfit-api
    build:
      context: ../..
      dockerfile: ../../Dockerfile
    container_name: core-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      APP_EMAIL_ENABLED: ${APP_EMAIL_ENABLED}
      APP_EMAIL_SENDER: ${APP_EMAIL_SENDER}
      APP_EMAIL_API_BASE_URL: ${APP_EMAIL_API_BASE_URL}
      APP_EMAIL_FRONTEND_BASE_URL: ${APP_EMAIL_FRONTEND_BASE_URL}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_SMTP_AUTH: ${SPRING_MAIL_SMTP_AUTH}
      SPRING_MAIL_SMTP_STARTTLS_ENABLE: ${SPRING_MAIL_SMTP_STARTTLS_ENABLE}
      SPRING_MAIL_SMTP_STARTTLS_REQUIRED: ${SPRING_MAIL_SMTP_STARTTLS_REQUIRED}
      SPRING_MAIL_SMTP_SSL_ENABLE: ${SPRING_MAIL_SMTP_SSL_ENABLE}
    networks:
      - calfit-net

networks:
  calfit-net:
    external: true