package com.coffiness.calfit.core.enums;

public enum NotificationType {
  ANNOUNCEMENT_CREATED,
  APPLICATION_PROCESS_CHANGED,
  INTERVIEW_REQUESTED,
  INTERVIEW_UPDATED,
  INTERVIEW_CANCELLED,
  SCHEDULE_INVITED,
  SCHEDULE_UPDATED,
  SCHEDULE_CANCELLED
}
